export {
  DEFAULT_COPY_TERMINAL_GUIDE,
  DEFAULT_PAGE_CREATE_SKILL_COMMAND,
  DEFAULT_INSPECT_COPY_SKILL_COMMAND,
  DEFAULT_MARK_CREATE_SKILL_COMMAND,
  DEFAULT_MARK_UPDATE_SKILL_COMMAND,
  DEFAULT_VIEWER_SKILLS,
} from '../../../constants/index.js';
